import type { AreaId, Criterion, Level } from './types'

/**
 * Catálogo de critérios v1 (DF-13 §4) — 51 critérios, 6 áreas × níveis 1–5.
 *
 * GOVERNANÇA (DF-13 §9): isto é código e muda por PR como qualquer regra do motor B6.
 * Todo critério novo nasce `oculto` se a fonte não existe; promover a `auto`/`declarado`
 * é mudança de versão. O campo `research` amarra cada linha à pesquisa de mercado
 * (`Pesquisa de Mercado/praticas-elite.md` = "prática N";
 *  `Pesquisa de Mercado/dificuldades-por-tier.md` = "dificuldade …") — sem essa âncora
 * o critério é calibração de gabinete, que é o risco nº 1 da feature (P-1.1).
 */
export const CATALOG_VERSION = '1.0.0'

/** Mudanças de catálogo aparecem na atividade da equipe com o delta explicado (P-1.3). */
export const CATALOG_CHANGELOG: readonly { version: string; note: string }[] = [
  { version: '1.0.0', note: 'Catálogo inicial (51 critérios) — DF-13 §4, pendente do piloto.' },
]

const c = (
  id: string,
  area: AreaId,
  level: Level,
  type: Criterion['type'],
  label: string,
  source: string,
  research: string,
  linkHint?: Criterion['linkHint'],
): Criterion => ({ id, area, level, type, label, source, research, linkHint })

export const CATALOG: readonly Criterion[] = [
  // ---------------------------------------------------------------- estrutura
  c(
    'EST-1.1',
    'estrutura',
    1,
    'auto',
    'Projeto de gaiola da equipe salvo na nuvem (≥ 1 versão)',
    'validador',
    'dificuldade iniciante: projeto vive em arquivo local de uma pessoa',
  ),
  c(
    'EST-2.1',
    'estrutura',
    2,
    'auto',
    'Gaiola completa: zero pendências de presença na última versão salva',
    'validador',
    'dificuldade iniciante: gaiola incompleta chega à inspeção',
  ),
  c(
    'EST-2.2',
    'estrutura',
    2,
    'declarado',
    'Seções e materiais conferidos com o que a equipe pretende fabricar',
    'capitania',
    'dificuldade iniciante: tubo comprado diverge do projetado',
  ),
  c(
    'EST-3.1',
    'estrutura',
    3,
    'auto',
    'Zero infrações automáticas na última versão salva',
    'validador',
    'prática 1: conformidade tratada como requisito de projeto, não de inspeção',
  ),
  c(
    'EST-3.2',
    'estrutura',
    3,
    'declarado',
    'Itens presenciais revisados em reunião, com registro',
    'capitania',
    'prática 1: revisão de conformidade em rito da equipe',
    'decision',
  ),
  c(
    'EST-4.1',
    'estrutura',
    4,
    'oculto',
    'Ficha da gaiola (Anexo B) gerada a partir do projeto validado',
    'ferramenta futura',
    'prática 4: documentação como entregável',
  ),
  c(
    'EST-4.2',
    'estrutura',
    4,
    'declarado',
    'Revisão do projeto da gaiola por outro membro, registrada',
    'capitania',
    'prática 3: revisão por pares',
    'decision',
  ),
  c(
    'EST-4.3',
    'estrutura',
    4,
    'declarado',
    'Análise estrutural (FEA) do chassi realizada e arquivada',
    'capitania',
    'prática 2: simulação antes da fabricação',
    'url',
  ),
  c(
    'EST-5.1',
    'estrutura',
    5,
    'declarado',
    'Gaiola fabricada conferida contra o projeto (as-built)',
    'capitania',
    'prática 6: controle entre projeto e peça fabricada',
    'url',
  ),
  c(
    'EST-5.2',
    'estrutura',
    5,
    'declarado',
    'Lições da inspeção técnica registradas no diário pós-competição',
    'capitania',
    'prática 10: ciclo de lições aprendidas',
    'decision',
  ),

  // ----------------------------------------------------------------- dinamica
  c(
    'DIN-1.1',
    'dinamica',
    1,
    'declarado',
    'Responsáveis de suspensão/direção e de trem de força definidos no organograma',
    'capitania',
    'dificuldade iniciante: subsistema sem dono',
  ),
  c(
    'DIN-2.1',
    'dinamica',
    2,
    'auto',
    'Ancoragens de suspensão apoiadas em tubo na última versão salva',
    'validador',
    'dificuldade iniciante: ancoragem no ar reprovada na inspeção',
  ),
  c(
    'DIN-2.2',
    'dinamica',
    2,
    'auto',
    'Ancoragem da direção apoiada, quando declarada no projeto',
    'validador',
    'dificuldade iniciante: fixação do volante fora de tubo',
  ),
  c(
    'DIN-3.1',
    'dinamica',
    3,
    'declarado',
    'Geometria de suspensão documentada (memória de cálculo arquivada)',
    'capitania',
    'prática 2: decisão de projeto com memória de cálculo',
    'url',
  ),
  c(
    'DIN-3.2',
    'dinamica',
    3,
    'declarado',
    'Setup de transmissão/CVT registrado por condição de uso',
    'capitania',
    'dificuldade intermediária: setup empírico não registrado',
    'guide',
  ),
  c(
    'DIN-4.1',
    'dinamica',
    4,
    'declarado',
    'Teste de bancada de ao menos um subsistema com resultado registrado',
    'capitania',
    'prática 5: testar antes de competir',
    'url',
  ),
  c(
    'DIN-4.2',
    'dinamica',
    4,
    'declarado',
    'Coleta de dados em pista (aquisição/telemetria) realizada ao menos uma vez',
    'capitania',
    'prática 8: decisão por dado medido',
    'url',
  ),
  c(
    'DIN-5.1',
    'dinamica',
    5,
    'declarado',
    'Aquisição de dados recorrente com análise pós-teste registrada',
    'capitania',
    'prática 8: aquisição como rotina, não evento',
    'decision',
  ),
  c(
    'DIN-5.2',
    'dinamica',
    5,
    'declarado',
    'Validação cruzada simulação × ensaio para ao menos um sistema',
    'capitania',
    'prática 2 + 5: simulação calibrada por ensaio',
    'url',
  ),

  // ------------------------------------------------------------- documentacao
  c(
    'DOC-1.1',
    'documentacao',
    1,
    'declarado',
    'Modelo dos relatórios da temporada definido',
    'capitania',
    'dificuldade iniciante: relatório começa do zero todo ano',
  ),
  c(
    'DOC-2.1',
    'documentacao',
    2,
    'declarado',
    'Relatório de projeto em escrita, com responsável por seção',
    'capitania',
    'prática 4: documentação com dono',
  ),
  c(
    'DOC-3.1',
    'documentacao',
    3,
    'declarado',
    'Relatório enviado no prazo da temporada',
    'capitania',
    'dificuldade intermediária: perda de pontos por atraso de entrega',
  ),
  c(
    'DOC-3.2',
    'documentacao',
    3,
    'declarado',
    'Memórias de cálculo arquivadas por subsistema',
    'capitania',
    'prática 2: memória de cálculo preservada',
    'url',
  ),
  c(
    'DOC-4.1',
    'documentacao',
    4,
    'declarado',
    'Revisão por pares de todas as seções antes do envio',
    'capitania',
    'prática 3: revisão por pares',
  ),
  c(
    'DOC-4.2',
    'documentacao',
    4,
    'oculto',
    'Ficha da gaiola (Anexo B) anexada ao pacote de documentos',
    'ferramenta futura',
    'prática 4: pacote de documentos completo',
  ),
  c(
    'DOC-5.1',
    'documentacao',
    5,
    'declarado',
    'Relatórios e memórias de temporadas anteriores acessíveis e indexados',
    'capitania',
    'prática 9: acervo geracional acessível',
    'url',
  ),

  // ---------------------------------------------------------------- fabricacao
  c(
    'FAB-1.1',
    'fabricacao',
    1,
    'declarado',
    'Acesso a oficina e processo de solda definidos (onde e quem)',
    'capitania',
    'dificuldade iniciante: fabricação terceirizada sem controle',
  ),
  c(
    'FAB-2.1',
    'fabricacao',
    2,
    'auto',
    'Gabaritos de boca de lobo gerados para o projeto da temporada',
    'validador',
    'dificuldade iniciante: corte de tubo por tentativa e erro',
  ),
  c(
    'FAB-2.2',
    'fabricacao',
    2,
    'declarado',
    'Plano de solda (sequência e fixação no gabarito) definido',
    'capitania',
    'prática 6: processo de fabricação planejado',
    'guide',
  ),
  c(
    'FAB-3.1',
    'fabricacao',
    3,
    'auto',
    'Sequência de solda publicada como guia da equipe',
    'conhecimento (guia com etiqueta "solda")',
    'prática 6 + prática 4: processo virou documento vivo',
  ),
  c(
    'FAB-3.2',
    'fabricacao',
    3,
    'declarado',
    'Controle dimensional pós-solda registrado',
    'capitania',
    'prática 6: verificação dimensional após fabricação',
    'url',
  ),
  c(
    'FAB-4.1',
    'fabricacao',
    4,
    'declarado',
    'Protocolo de testes pré-competição executado e registrado',
    'capitania',
    'prática 5: shakedown e teste de freio antes da competição',
    'guide',
  ),
  c(
    'FAB-5.1',
    'fabricacao',
    5,
    'declarado',
    'Carro anterior usado como mula de testes ou bancada própria em operação',
    'capitania',
    'prática 7: frota de testes',
    'url',
  ),

  // -------------------------------------------------------------------- gestao
  c(
    'GES-1.1',
    'gestao',
    1,
    'auto',
    'Capitania regular e organograma criado',
    'organograma',
    'dificuldade iniciante: liderança informal e difusa',
  ),
  c(
    'GES-2.1',
    'gestao',
    2,
    'auto',
    'Todos os cargos de liderança do organograma com ocupante',
    'organograma',
    'dificuldade iniciante: subsistema órfão',
  ),
  c(
    'GES-2.2',
    'gestao',
    2,
    'declarado',
    'Rotina de reunião da equipe definida (frequência e formato)',
    'capitania',
    'prática 3: cadência de reunião',
  ),
  c(
    'GES-3.1',
    'gestao',
    3,
    'auto',
    'Temporada configurada no portal, com marcos datados',
    'temporada',
    'prática 3: planejamento com marcos e prazo',
  ),
  c(
    'GES-3.2',
    'gestao',
    3,
    'declarado',
    'Orçamento da temporada elaborado',
    'capitania',
    'dificuldade intermediária: caixa sem previsão',
    'url',
  ),
  c(
    'GES-4.1',
    'gestao',
    4,
    'declarado',
    'Trainees avaliados formalmente antes da efetivação',
    'capitania',
    'prática 9: formação de novatos com critério',
  ),
  c(
    'GES-4.2',
    'gestao',
    4,
    'declarado',
    'Carteira de apoiadores ativa (≥ 2 parcerias) registrada',
    'capitania',
    'dificuldade intermediária: patrocínio pontual, sem carteira',
    'url',
  ),
  c(
    'GES-5.1',
    'gestao',
    5,
    'declarado',
    'Processo seletivo estruturado (edital/funil) praticado',
    'capitania',
    'prática 9: recrutamento como processo da equipe',
    'guide',
  ),
  c(
    'GES-5.2',
    'gestao',
    5,
    'declarado',
    'Prestação de contas da temporada apresentada à equipe',
    'capitania',
    'prática 3: gestão como pequena empresa',
    'decision',
  ),

  // -------------------------------------------------------------- conhecimento
  c(
    'CON-1.1',
    'conhecimento',
    1,
    'auto',
    'Ao menos uma decisão registrada no diário',
    'conhecimento',
    'dificuldade nº 1 (rotatividade): a decisão morre no WhatsApp',
  ),
  c(
    'CON-2.1',
    'conhecimento',
    2,
    'auto',
    'Ao menos 10 decisões e 2 guias publicados',
    'conhecimento',
    'prática 4: registro é hábito, não evento',
  ),
  c(
    'CON-2.2',
    'conhecimento',
    2,
    'auto',
    'Trilha de integração de novatos publicada',
    'conhecimento',
    'prática 9: integração estruturada de novatos',
  ),
  c(
    'CON-3.1',
    'conhecimento',
    3,
    'auto',
    'Último novato aprovado concluiu a trilha de integração',
    'conhecimento',
    'prática 9: a trilha existe E é percorrida',
  ),
  c(
    'CON-3.2',
    'conhecimento',
    3,
    'auto',
    'Decisões registradas em ao menos 3 áreas distintas nos últimos 6 meses',
    'conhecimento',
    'prática 4: registro cobre a equipe inteira, não um subsistema',
  ),
  c(
    'CON-4.1',
    'conhecimento',
    4,
    'auto',
    'Um kit de passagem concluído e nenhum kit aberto com data de saída vencida',
    'conhecimento',
    'dificuldade nº 1 (rotatividade): saída sem passagem de bastão',
  ),
  c(
    'CON-4.2',
    'conhecimento',
    4,
    'auto',
    'Nenhum guia órfão: todos com dono e atualização há menos de 6 meses',
    'conhecimento',
    'prática 4: documento vivo tem dono',
  ),
  c(
    'CON-5.1',
    'conhecimento',
    5,
    'declarado',
    'Ritual de lições aprendidas pós-competição realizado, com registro',
    'capitania',
    'prática 10: retrospectiva de temporada',
    'decision',
  ),
  c(
    'CON-5.2',
    'conhecimento',
    5,
    'declarado',
    'Memória de gerações mantida (histórico de funções e alumni)',
    'capitania',
    'prática 9: continuidade entre gerações',
  ),
]

const BY_ID = new Map(CATALOG.map((cr) => [cr.id, cr]))

export function criterionById(id: string): Criterion | undefined {
  return BY_ID.get(id)
}

/** Critérios da área, sem os `oculto` (fora do denominador — DF-13 RF-1.2). */
export function visibleCriteria(area: AreaId): Criterion[] {
  return CATALOG.filter((cr) => cr.area === area && cr.type !== 'oculto')
}
